app/__init__.py
from flask import Flask

from app.routes.nombres import bp_nombres


from app.config import Config


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    app.register_blueprint(bp_nombres)

    return app

app/routes/episoa.py
import requests
'''
url = "https://rickandmortyapi.com/api/episode/2"

datos = requests.get(url).json()


for a in datos['characters']:

    nombres = a

    mirar = requests.get(nombres).json()
    print("Nombre",mirar['name'])
    print("TYPO ",mirar['type'])

    if mirar['location']["url"] == "":
        print("htts:sae")
    else:
        print(mirar['location']["url"])
        localidad = mirar['location']["url"]

    local_dato = requests.get(localidad).json()
    r = requests.get(localidad)

    print(local_dato)
    if r.status_code=="404":
        print("ERROR")
    else:
        print("Dimension : ", local_dato['dimension'])

    print("--------")

'''
from app.modelos.capitulo import Capitulo
from app.db import db



link = "https://rickandmortyapi.com/api/episode/"

for numerador in range(1,52):
    url=link+str(numerador)

    datos = requests.get(url).json()

    for a in datos['characters']:

        nombres = a

        mirar = requests.get(nombres).json()
        nommbre = mirar['name']
        tyypo = mirar['type']
        fotoss = mirar['image']

        if mirar['location']["url"] == "":
            print("htts:sae")
        else:
            mirar['location']["url"]
            localidad = mirar['location']["url"]

        local_dato = requests.get(localidad).json()
        r = requests.get(localidad)

        # print(local_dato)
        if r.status_code == "404":
            print("ERROR")
        else:

            llenado_capitulo = Capitulo(numerador, nommbre, tyypo, local_dato['dimension'], fotoss)

            db.Capitulo.insert_one(llenado_capitulo.to_json())

            # print("Nombre", nommbre, "Typo:", tyypo, "Dimension : ", local_dato['dimension'])

        print("--------")

app/routes/lisaes.py
import requests





for a in range(1,22):
    url ="https://rickandmortyapi.com/api/character?page="+str(a)
    datos = requests.get(url).json()

    for a in datos['results']:
        print(a)

app/routes/nombres.py
from flask import Blueprint, render_template
import requests


from app.modelos.personajes import Personaje
from app.modelos.capitulo import Capitulo

from app.db import db

bp_nombres = Blueprint('bp_nombres', __name__)


@bp_nombres.route("/")
def index():
    morty = db.Personaje.find({}).sort("name", 1)
    return render_template("index.html", morty=morty)


@bp_nombres.route("/datos/<int:id>")
def datos(id):
    detalles = db.Personaje.find({'id': id})
    return render_template('base.html', detalles=detalles)



@bp_nombres.route("/capítulo/<int:id>")
def deta_cap(id):
    captituloss = db.Capitulo.find({'id': id}).sort("name", 1)

    return render_template('capitulos.html', captituloss=captituloss)



@bp_nombres.route("/importacion")
def lista_nombres():
    import requests

    for a in range(1, 22):
        url = "https://rickandmortyapi.com/api/character?page=" + str(a)
        datos = requests.get(url).json()

        for lise in datos['results']:
            llenado_personaje = Personaje(
                lise['id'],
                lise['name'],
                lise['status'],
                lise['species'],
                lise['type'],
                lise['gender'],
                lise['image'],
        )
            db.Personaje.insert_one(llenado_personaje.to_json())

    return "MUESTRO EN EL TERMINAL"


@bp_nombres.route("/llenado_cap")
def lista_capitulo():
    link = "https://rickandmortyapi.com/api/episode/"

    for numerador in range(1,52):
        url=link+str(numerador)

        datos = requests.get(url).json()

        for a in datos['characters']:

            nombres = a

            mirar = requests.get(nombres).json()
            nommbre = mirar['name']
            tyypo = mirar['type']
            fotoss = mirar['image']

            if mirar['location']["url"] == "":
                print("htts:sae")
            else:
                mirar['location']["url"]
                localidad = mirar['location']["url"]

            local_dato = requests.get(localidad).json()
            r = requests.get(localidad)

            # print(local_dato)
            if r.status_code == "404":
                print("ERROR")
            else:

                llenado_capitulo = Capitulo(numerador, nommbre, tyypo, local_dato['dimension'], fotoss)

                db.Capitulo.insert_one(llenado_capitulo.to_json())

                # print("Nombre", nommbre, "Typo:", tyypo, "Dimension : ", local_dato['dimension'])

            print("--------")

app/routes/nums.py
url = "https://rickandmortyapi.com/api/episode/"

for a in range(1,52):
    print(url+str(a))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% for unidad in detalles %}

        <a href="{{ url_for('bp_nombres.index') }}">REGRESAR</a>

        <th><h3>NOMBRE: {{ unidad.name }}</a> </h3></th>
            </tr>
            <tr>
                <th><h3>ESPECIE: {{ unidad.species }}</h3></th>
            </tr>
            <tr>
                <th><h3>ESTADO: {{ unidad.status }}</h3></th>
            </tr>
                <th><h3>Genero: {{ unidad.gender }}</h3></th>
            <tr>
                <th><h3>LOCALIDAD: {{ unidad.location }}</h3></th>
            </tr>

            <td>
            <th>




                <img src=" {{ unidad.image }}" >
            </th>
            </td>
{% endfor %}








</body>
</html>

app/templates/capitulos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">TIPO</th>
      <th scope="col">DIMENSION</th>
      <th scope="col">FOTO</th>
    </tr>
  </thead>
  {% for a in captituloss%}
  <tbody>
    <tr>
      <th scope="row">{{a ['name']}}</th>
      <td>{{a ['type']}}</td>
      <td>{{a ['dimension']}}</td>
      <td><img src="{{a ['foto']}}" height="100" width="100"></td>
    </tr>
  </tbody>
    {% endfor %}
</table>

</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>




<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">ESTADO</th>
      <th scope="col">ESPECIE</th>
      <th scope="col">ESTADO</th>
      <th scope="col">GENERO</th>
      <th scope="col">IMAGEN</th>
    </tr>
  </thead>
   {% for unidad in morty %}
  <tbody>
    <tr>
      <th scope="row"><a href="{{ url_for('bp_nombres.datos', id =unidad.id ) }}">{{ unidad.name }}</a></th>
      <td><h3> {{ unidad.status }}</h3></td>
      <td><h3>{{ unidad.species }}</h3></td>
       <td><h3>{{ unidad.type }}</h3></td>
       <td><h3>{{ unidad.gender }}</h3></td>
      <td><img src=" {{ unidad.image }}" width="100" height="100"></td>
    </tr>
  </tbody>
    {% endfor %}
</table>














</body>
</html>

app/templates/indexse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DATOS  </title>
</head>
<body>


{% for a in morty %}
    {%for unidad in a.results%}
        <table class="default" border="1" align="center">
            <tr>
                <th>PERSONAJES</th>
            </tr>
            <tr>
                <th><h3>NOMBRE: <a href="{{ url_for('bp_nombres.datos', id =unidad.id ) }}">{{ unidad.name }}</a> </h3></th>
            </tr>
            <tr>
                <th><h3>ESPECIE: {{ unidad.species }}</h3></th>
            </tr>
            <tr>
                <th><h3>ESTADO: {{ unidad.status }}</h3></th>
            </tr>
                <th><h3>Genero: {{ unidad.gender }}</h3></th>
            <tr>
                <th><h3>LOCALIDAD: {{ unidad.location.name }}</h3></th>
            </tr>

            <td>
            <th>
                <img src=" {{ unidad.image }}" ></img>
            </th>
            </td>

        </table>
    {% endfor %}
{% endfor %}

</body>
</html>